# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cd7863b79cd51b03899af6ddfe7b907ab3a70a35e8517f425c6d57e7303b2c8e804049ecb78a9ddd43016711dba1496491a5b0ca51ac05da474cc399f1933b9d

test:
  secret_key_base: 7f2367330ed3dacba6b5bc67ba02aa14b80d45365a86f47277a1de0edac1f67b72fd975274b1a2f48a88929164085d8fe57c77c3bdf3433906a011ff627080ed

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
